import 'chemical_element.dart';

class ElementsList {
  List<ChemicalElement> elementsList = [
    ChemicalElement("Hidrogênio", "H", 1, "blabla",),
    ChemicalElement("Hélio", "He", 2, "blabla"),
    ChemicalElement("Lítio", "Li", 3, "blabla",),
    ChemicalElement("Berílio", "Be", 4, "blabla",),
    ChemicalElement("Boro", "B", 5, "blabla",),
    ChemicalElement("Carbono", "C", 1, "blabla",),
    ChemicalElement("Nitrogênio", "N", 1, "blabla",),
    ChemicalElement("Oxigênio", "O", 1, "blabla",),
    ChemicalElement("Flúor", "F", 6, "blabla",),
    ChemicalElement("Neônio", "Ne", 2, "blabla",),
    ChemicalElement("Sódio", "Na", 3, "blabla",),
    ChemicalElement("Magnésio", "Mg", 4, "blabla",),
    ChemicalElement("Alumínio", "Al", 7, "blabla",),
    ChemicalElement("Silício", "Si", 5, "blabla",),
    ChemicalElement("Fósforo", "P", 1, "blabla",),
    ChemicalElement("Enxofre", "S", 1, "blabla",),
    ChemicalElement("Cloro", "Cl", 6, "blabla",),
    ChemicalElement("Argônio", "Ar", 2, "blabla",),
    ChemicalElement("Potássio", "K", 3, "blabla",),
    ChemicalElement("Cálcio", "Ca", 4, "blabla",),
    ChemicalElement("Escândio", "Sc", 8, "blabla",),
    ChemicalElement("Titânio", "Ti", 8, "blabla",),
    ChemicalElement("Vanádio", "V", 8, "blabla",),
    ChemicalElement("Crômio", "Cr", 8, "blabla",),
    ChemicalElement("Manganês", "Mn", 8, "blabla",),
    ChemicalElement("Ferro", "Fe", 8, "blabla",),
    ChemicalElement("Cobalto", "Co", 8, "blabla",),
    ChemicalElement("Níquel", "Ni", 8, "blabla",),
    ChemicalElement("Cobre", "Cu", 8, "blabla",),
    ChemicalElement("Zinco", "Zn", 8, "blabla",),
    ChemicalElement("Gálio", "Ga", 7, "blabla",),
    ChemicalElement("Germânio", "Ge", 5, "blabla",),
    ChemicalElement("Arsênio", "As", 5, "blabla",),
    ChemicalElement("Selênio", "Se", 1, "blabla",),
    ChemicalElement("Bromo", "Br", 6, "blabla",), 
    ChemicalElement("Criptônio", "Kr", 2, "blabla",),
    ChemicalElement("Rubídio", "Rb", 3, "blabla",),
    ChemicalElement("Estrôncio", "Sr", 4, "blabla",),
    ChemicalElement("Ítrio", "Y", 8, "blabla",),
    ChemicalElement("Zircônio", "Zr", 8, "blabla",),
    ChemicalElement("Nióbio", "Nb", 8, "blabla",),
    ChemicalElement("Molibdênio", "Mo", 8, "blabla",),
  ];
}